language: cpp
compiler:
- gcc
matrix:
  include:
  # - os: linux
  - os: osx
    before_install:
    - export LDFLAGS="-L/usr/local/opt/openssl/lib"
    - export CPPFLAGS="-I/usr/local/opt/openssl/include"
    - export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
  - os: windows
    before_install:
    - choco install make 
script:
- make


export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"
For pkg-config to find openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"